// <auto-generated />
using MUNAdmin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MUNAdmin.Migrations
{
    [DbContext(typeof(MUNAdminContext))]
    [Migration("20260718192526_0718")]
    partial class _0718
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MUNAdmin.Models.MUNInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MUNAccessCode")
                        .HasColumnType("int");

                    b.Property<string>("MUNTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MUNInstance");
                });

            modelBuilder.Entity("MUNAdmin.Models.MUNInstance", b =>
                {
                    b.OwnsMany("MUNAdmin.Models.DelegationInstance", "DelegationList", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("DelegationAccsesCode")
                                .HasColumnType("int");

                            b1.Property<string>("DelegationCountry")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("MUNInstanceId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("MUNInstanceId");

                            b1.ToTable("DelegationInstance");

                            b1.WithOwner()
                                .HasForeignKey("MUNInstanceId");

                            b1.OwnsMany("MUNAdmin.Models.DelegationCouncil", "CouncilList", b2 =>
                                {
                                    b2.Property<int>("DelegationInstanceId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("AmendmentPoints")
                                        .HasColumnType("int");

                                    b2.Property<int>("RebuttalPoints")
                                        .HasColumnType("int");

                                    b2.Property<bool>("RequestedRebuttal")
                                        .HasColumnType("bit");

                                    b2.HasKey("DelegationInstanceId", "Id");

                                    b2.ToTable("DelegationCouncil");

                                    b2.WithOwner()
                                        .HasForeignKey("DelegationInstanceId");

                                    b2.OwnsOne("MUNAdmin.Models.CouncilInformation", "Council", b3 =>
                                        {
                                            b3.Property<int>("DelegationCouncilDelegationInstanceId")
                                                .HasColumnType("int");

                                            b3.Property<int>("DelegationCouncilId")
                                                .HasColumnType("int");

                                            b3.Property<string>("CouncilName")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<string>("PrimaryColor")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<string>("SecondaryColor")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.HasKey("DelegationCouncilDelegationInstanceId", "DelegationCouncilId");

                                            b3.ToTable("DelegationCouncil");

                                            b3.WithOwner()
                                                .HasForeignKey("DelegationCouncilDelegationInstanceId", "DelegationCouncilId");
                                        });

                                    b2.Navigation("Council")
                                        .IsRequired();
                                });

                            b1.Navigation("CouncilList");
                        });

                    b.OwnsMany("MUNAdmin.Models.CouncilInformation", "CouncilInformationList", b1 =>
                        {
                            b1.Property<int>("MUNInstanceId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("CouncilName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PrimaryColor")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SecondaryColor")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("MUNInstanceId", "Id");

                            b1.ToTable("MUNInstance_CouncilInformationList");

                            b1.WithOwner()
                                .HasForeignKey("MUNInstanceId");
                        });

                    b.Navigation("CouncilInformationList");

                    b.Navigation("DelegationList");
                });
#pragma warning restore 612, 618
        }
    }
}
