// <auto-generated />
using MUNAdmin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MUNAdmin.Migrations
{
    [DbContext(typeof(MUNAdminContext))]
    partial class MUNAdminContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MUNAdmin.Models.CouncilInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AcceptingAmmendments")
                        .HasColumnType("bit");

                    b.Property<bool>("AcceptingRebuttals")
                        .HasColumnType("bit");

                    b.Property<string>("CouncilName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradientPrimaryColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradientSecondaryColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInSession")
                        .HasColumnType("bit");

                    b.Property<int>("MUNInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MUNInstanceId");

                    b.ToTable("CouncilInformation");
                });

            modelBuilder.Entity("MUNAdmin.Models.MUNInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MUNAccessCode")
                        .HasColumnType("int");

                    b.Property<string>("MUNTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MUNInstance");
                });

            modelBuilder.Entity("MUNAdmin.Models.CouncilInformation", b =>
                {
                    b.HasOne("MUNAdmin.Models.MUNInstance", null)
                        .WithMany("CouncilInformationList")
                        .HasForeignKey("MUNInstanceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsMany("MUNAdmin.Models.Resolution", "Resolutions", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("BodyText")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("CouncilInformationId")
                                .HasColumnType("int");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("CouncilInformationId");

                            b1.ToTable("Resolution");

                            b1.WithOwner()
                                .HasForeignKey("CouncilInformationId");
                        });

                    b.Navigation("Resolutions");
                });

            modelBuilder.Entity("MUNAdmin.Models.MUNInstance", b =>
                {
                    b.OwnsMany("MUNAdmin.Models.DelegationInstance", "DelegationList", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("DelegationAccsesCode")
                                .HasColumnType("int");

                            b1.Property<string>("DelegationCountry")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("MUNInstanceId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("MUNInstanceId");

                            b1.ToTable("DelegationInstance");

                            b1.WithOwner()
                                .HasForeignKey("MUNInstanceId");

                            b1.OwnsMany("MUNAdmin.Models.DelegationCouncil", "CouncilList", b2 =>
                                {
                                    b2.Property<int>("DelegationInstanceId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("AmendmentPoints")
                                        .HasColumnType("int");

                                    b2.Property<int>("CouncilId")
                                        .HasColumnType("int");

                                    b2.Property<int>("RebuttalPoints")
                                        .HasColumnType("int");

                                    b2.Property<bool>("RequestedRebuttal")
                                        .HasColumnType("bit");

                                    b2.HasKey("DelegationInstanceId", "Id");

                                    b2.HasIndex("CouncilId");

                                    b2.ToTable("DelegationCouncil");

                                    b2.HasOne("MUNAdmin.Models.CouncilInformation", "Council")
                                        .WithMany()
                                        .HasForeignKey("CouncilId")
                                        .OnDelete(DeleteBehavior.NoAction)
                                        .IsRequired();

                                    b2.WithOwner()
                                        .HasForeignKey("DelegationInstanceId");

                                    b2.OwnsMany("MUNAdmin.Models.Ammendment", "Ammendments", b3 =>
                                        {
                                            b3.Property<int>("DelegationCouncilDelegationInstanceId")
                                                .HasColumnType("int");

                                            b3.Property<int>("DelegationCouncilId")
                                                .HasColumnType("int");

                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("int");

                                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b3.Property<int>("Id"));

                                            b3.Property<string>("ChangeClauseNumber")
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<string>("NewText")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<int>("ResolutionID")
                                                .HasColumnType("int");

                                            b3.HasKey("DelegationCouncilDelegationInstanceId", "DelegationCouncilId", "Id");

                                            b3.ToTable("Ammendment");

                                            b3.WithOwner()
                                                .HasForeignKey("DelegationCouncilDelegationInstanceId", "DelegationCouncilId");
                                        });

                                    b2.Navigation("Ammendments");

                                    b2.Navigation("Council");
                                });

                            b1.Navigation("CouncilList");
                        });

                    b.Navigation("DelegationList");
                });

            modelBuilder.Entity("MUNAdmin.Models.MUNInstance", b =>
                {
                    b.Navigation("CouncilInformationList");
                });
#pragma warning restore 612, 618
        }
    }
}
